name: Deploy Angular to Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npx ng build --configuration production --base-href /restoapp/

      - name: Prepare for GitHub Pages
        run: |
          cd dist/restoapp/browser
          mv index.csr.html index.html || echo "Ya se llama index.html"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/restoapp/browser

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
